name: Publish on PyPI

on:
  push:
    tags: '*'

jobs:

  pypi-publishing:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install PyPA build
      run: python3 -m pip install build

    - name: Prepare distribuition
      run: python3 -m build

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TWINE_PASSWORD }}
